# Generated by Django 4.2.6 on 2023-11-21 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_product_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='digital',
        ),
    ]
